version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/dubli/taskbox
    steps:
      - checkout
      #Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Remove node_modules
          command: rm -rf node_modules
      - run:
          name: Running npm install
          command: npm install --only=dev
      - persist_to_workspace:
          root: ~/dubli
          paths:
            - taskbox
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/dubli/taskbox
    steps:
      - run:
          command: echo "test"
    #   - attach_workspace:
    #       at: ~/dubli
    #   - run:
    #       name: Install node 0.12.7
    #       command:
    #           ./node_modules/deploy-scripts/node.sh
    #   - run:
    #       name: Performing test
    #       command: ./node_modules/deploy-scripts/test.sh
  deploy-dev:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/dubli/taskbox
    environment:
      ENV: "dev"
      APP_NAME: "taskbox"
      DEPLOYMENT_GROUP: "dev-taskbox"
      REVISION_S3_BUCKET: "codedeploy-bucket-352228731405"
      REVISION_KEY_PATTERN: "taskbox"
      FILES_TO_COPY: "package.json,npm-shrinkwrap.json,configs.json,appspec.yml,src/,scripts/"
    steps:
      - attach_workspace:
          at: ~/dubli
      - run:
          name: Deploy if tests pass and branch is Dev
          command: echo Building Dev
      - run:
          name: Install aws-cli
          command:
              ./node_modules/deploy-scripts/aws-cli.sh
      - run:
          name: Install node 0.12.7
          command:
              ./node_modules/deploy-scripts/node.sh
      - run:
          name: Building Application
          command:
              ./node_modules/deploy-scripts/ec2-build.sh
      - run:
          name: Deploying apllication to aws ec2 instances
          command:
              ./node_modules/deploy-scripts/ec2-deploy.sh
  deploy-stage:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/dubli/taskbox
    environment:
      ENV: "stage"
      APP_NAME: "taskbox"
      DEPLOYMENT_GROUP: "stage-taskbox"
      REVISION_S3_BUCKET: "codedeploy-bucket-352228731405"
      REVISION_KEY_PATTERN: "taskbox"
      FILES_TO_COPY: "package.json,npm-shrinkwrap.json,configs.json,appspec.yml,src/,scripts/"
    steps:
      - attach_workspace:
          at: ~/dubli
      - run:
          name: Deploy if tests pass and branch is Dev
          command: echo Building Dev
      - run:
          name: Install aws-cli
          command:
              ./node_modules/deploy-scripts/aws-cli.sh
      - run:
          name: Install node 0.12.7
          command:
              ./node_modules/deploy-scripts/node.sh
      - run:
          name: Building Application
          command:
              ./node_modules/deploy-scripts/ec2-build.sh
      - run:
          name: Deploying apllication to aws ec2 instances
          command:
              ./node_modules/deploy-scripts/ec2-deploy.sh
  deploy-prod:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/dubli/taskbox
    environment:
      ENV: "prod"
      APP_NAME: "taskbox"
      DEPLOYMENT_GROUP: "prod-taskbox"
      REVISION_S3_BUCKET: "codedeploy-bucket-352228731405"
      REVISION_KEY_PATTERN: "taskbox"
      FILES_TO_COPY: "package.json,npm-shrinkwrap.json,configs.json,appspec.yml,src/,scripts/"
    steps:
      - attach_workspace:
          at: ~/dubli
      - run:
          name: Deploy if tests pass and branch is Prod
          command:
              echo Building Prod
      - run:
          name: Install aws-cli
          command:
              ./node_modules/deploy-scripts/aws-cli.sh
      - run:
          name: Install node 0.12.7
          command:
              ./node_modules/deploy-scripts/node.sh
      - run:
          name: Building Application
          command:
              ./node_modules/deploy-scripts/ec2-build.sh
      - run:
          name: Deploying apllication to aws ec2 instances
          command:
              ./node_modules/deploy-scripts/ec2-deploy.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: dev
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: dev
      - deploy-stage:
          requires:
            - build
          filters:
            branches:
              only: stage
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: prod
